---
title: "dailynews"
output: html_document
---

```{r}
library(tm)
library(RWeka)
library(magrittr)
library(Matrix)
library(glmnet)
library(ROCR)
library(ggplot2)
price<-read.csv("DJIA_table.csv",header=T)
data<-read.csv("Combined_News_DJIA.csv",header=T)

```

```{r}
data$Date <- as.Date(data$Date)
data$all <- paste(data$Top1, data$Top2, data$Top3, data$Top4, data$Top5, data$Top6,
                  data$Top7, data$Top8, data$Top9, data$Top10, data$Top11, data$Top12, 
                  data$Top13, data$Top14, data$Top15, data$Top16, data$Top17, data$Top18,
                  data$Top19, data$Top20, data$Top21, data$Top22, data$Top23, data$Top24,
                  data$Top25, sep='<s>')

# Get rid of those pesky b's and backslashes 
data$all <- gsub('b"|b\'|\\\\|\\"', "", data$all)

# Get rid of all punctuation except headline separators
data$all <- gsub("([<>])|[[:punct:]]", "\\1", data$all)

# Reduce to only the three columns we need. 
data <- data[, c('Date', 'Label', 'all')]
```


```{r}
control <- list(
    removeNumbers = TRUE,
    tolower = TRUE,
    # exclude stopwords and headline tokens
    stopwords = c(stopwords(kind = 'SMART'), '<s>')
)


dtm <- Corpus(VectorSource(data$all)) %>% 
    DocumentTermMatrix(control=control)
```

```{r}
split_index <- data$Date <= '2014-12-31'


ytrain <- as.factor(data$Label[split_index])
stock_train<-diff(log(price$Close[split_index]))
xtrain <- Matrix(as.matrix(dtm)[split_index, ], sparse=TRUE)[-1,]


ytest <- as.factor(data$Label[!split_index])
stock_test<-diff(log(price$Close[!split_index]))
xtest <- Matrix(as.matrix(dtm)[!split_index, ], sparse=TRUE)[-1,]
```

```{r}
max-ppsize<-5000000
```


```{r,warning=FALSE}
Train<-as.data.frame(as.matrix(cbind(xtrain,stock_train)))
LR_fit<-lm(stock_train~.,data=Train)
LR_fit


```


```{r,warning=FALSE}
# Train the model
glmnet.fit <- cv.glmnet(x=xtrain, y=stock_train, alpha=0)

# Generate predictions
preds <- predict(glmnet.fit, newx=xtest, type='response', s='lambda.min')

# Put results into dataframe for plotting.
results <- data.frame(pred=preds, actual=stock_test)
```



